spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:postgresql://localhost:5439/playlocal
    username: playlocal
    password: playlocal

  jpa:
    show-sql: true
    open-in-view: true

  flyway:
    baseline-on-migrate: true

logging:
  level:
    root: DEBUG
    com.backend.playlocal: DEBUG
    org.hibernate.SQL: DEBUG

mail:
  enabled: false

recaptcha:
  enabled: false