# Generated by Django 5.2.7 on 2025-11-09 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('decisionStatus', models.CharField(max_length=100)),
                ('projectStatus', models.CharField(max_length=100)),
                ('architect', models.CharField(blank=True, max_length=255, null=True)),
                ('units', models.CharField(blank=True, max_length=50, null=True)),
                ('floors', models.CharField(blank=True, max_length=50, null=True)),
                ('buildingCategories', models.JSONField(default=list)),
                ('buildingTypes', models.JSONField(default=list)),
                ('lastUpdate', models.DateField()),
                ('media', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
