# Generated by Django 5.2.7 on 2025-11-10 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='projectStatus',
            field=models.IntegerField(choices=[(0, 'Planned'), (1, 'In Progress'), (2, 'Completed'), (3, 'Cancelled')], default=0),
        ),
    ]
