name: Deploy Backend on Render

# Trigger on push to release branch
on:
  push:
    branches:
      - release

jobs:
  render-deploy:
    runs-on: ubuntu-latest
    steps:
      # Trigger Render deployment
      - name: Trigger Render Deploy
        run: |
          curl -X POST "https://api.render.com/deploy/srv-d5h9kpkhg0os73frr6tg?key=xo92pjp9tkM"
