name: Release

on:
  push:
    tags:
      - 'r*'   # triggers when you push tags like r1.0.0 or r1

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
